//! Baking a [`TextureSpec`] to GPU textures (DESIGN §7's baked path).
//!
//! > *Baked (baseline): rendered once to an RGBA8 texture at tier-scaled
//! > resolution at load time. This is a fragment pass, not compute — it works
//! > fully within WebGL2 limits (bake resolution capped at 2048² there).* — §7
//!
//! One spec produces **two** targets, from one octave loop:
//!
//! ```text
//!   TextureSpec ──► vs_bake (fullscreen triangle)
//!                     ├─ fs_albedo ─► RGBA8, ramp-mapped colour ─┐
//!                     └─ fs_normal ─► RGBA8, packed normal ──────┤
//!                                                                │
//!                     ┌──────────── mip chain ───────────────────┘
//!                     ├─ fs_mip_color  ─► level i+1 from level i (2×2 box)
//!                     └─ fs_mip_normal ─► same, unpacked → averaged →
//!                                          renormalized → repacked
//! ```
//!
//! Two single-target passes rather than one MRT pass: two colour attachments
//! would also fit `downlevel_webgl2_defaults`, but a single attachment is the
//! shape every backend agrees on without thinking about it, and this is
//! load-time work the content cache mostly skips.
//!
//! ## Mipmaps (DESIGN §7, §11)
//!
//! Every baked target carries a full chain down to 1×1, generated at bake time
//! by a render-pass downsample — no compute, no storage textures, nothing
//! WebGL2 lacks. Without it every sample reads level 0 regardless of how many
//! world metres a pixel covers, which shows up as *shimmer* at distance (the
//! texture is minified and point-picked out of a field it is under-sampling)
//! and, indirectly, as *blur* up close, because the only way to fight the
//! shimmer was to author a tile so large that its texel density collapsed.
//!
//! The chain costs 1/3 more memory and 1/3 more cached bytes, and roughly
//! `2·log2(resolution)` extra render passes over targets that halve each time —
//! a few percent of a bake.
//!
//! ## Caching (DESIGN §6's invariant, applied one level down)
//!
//! Layered exactly like the mesh cache, and under the same rule: **the cache is
//! purely an optimization; deleting it must not change a pixel.**
//!
//! ```text
//!   TextureHandle (= content_key)
//!        ├─ in memory  → TextureRegistry: handle → GPU textures + bind group
//!        └─ persistent → CacheStore::load_texture: handle → raw RGBA8 bytes
//! ```
//!
//! A store entry is untrusted: it carries a format version, the `postcard`
//! bytes of the spec it was baked from and its resolution, and anything that
//! does not match exactly — wrong version, wrong size, stale layout, key
//! collision, hostile file — is discarded and rebaked.
//! `tests/texture_cache.rs` runs cold, warm and deleted-mid-run and demands
//! byte-identical pixels from all three.
//!
//! Reading pixels back off the GPU needs a blocking device poll, which is not
//! available on the web. Stores therefore opt in with
//! [`CacheStore::caches_textures`]; the default is `false`, so the web's
//! [`NoopCache`](crate::cache::NoopCache) path never tries.

use std::collections::HashMap;

use bytemuck::{Pod, Zeroable};
use serde::{Deserialize, Serialize};

use crate::cache::CacheStore;
use crate::texture::{TextureHandle, TextureSpec, MAX_OCTAVES, MAX_RAMP_STOPS};

/// The noise library. Prepended to this pass by [`bake_shader_source`] and to
/// every material variant by
/// [`material::variant_source`](crate::material::variant_source), because §7's
/// live path evaluates the identical field in the fragment shader.
pub const NOISE_SHADER: &str = include_str!("noise.wgsl");

/// The bake pass. Not standalone — see [`bake_shader_source`].
pub const BAKE_SHADER: &str = include_str!("bake.wgsl");

/// Both baked targets are RGBA8. Not sRGB: runt has no colour management, so a
/// baked albedo is in exactly the space `Material::base_color` is in, and the
/// normal target must be linear regardless.
pub const BAKE_FORMAT: wgpu::TextureFormat = wgpu::TextureFormat::Rgba8Unorm;

/// The bake shader, with the noise library prepended.
///
/// The dumbest possible include, matching
/// [`material::variant_source`](crate::material::variant_source)'s philosophy:
/// no `#include` grammar, no token scanning, just a concatenation — so both
/// files stay ordinary readable WGSL.
pub fn bake_shader_source() -> String {
    let mut out = String::with_capacity(NOISE_SHADER.len() + BAKE_SHADER.len() + 64);
    out.push_str("// generated by runt_core::bake::bake_shader_source\n");
    out.push_str(NOISE_SHADER);
    out.push('\n');
    out.push_str(BAKE_SHADER);
    out
}

// ---------------------------------------------------------------------------
// The uniform
// ---------------------------------------------------------------------------

/// `@group(0)` of the bake pass. Field order is restated in `bake.wgsl`.
///
/// The octave table is *planned on the CPU* ([`TextureSpec::octave_plan`]), so
/// the shader contains no `pow`, no rounding rule and no lattice-period
/// arithmetic it could get subtly different from the Rust twin.
#[repr(C)]
#[derive(Clone, Copy, Debug, Pod, Zeroable)]
pub struct BakeUniform {
    /// lattice, cell return type, fractal, octave count.
    pub mode: [u32; 4],
    /// normal mode, ramp stop count, unused, unused.
    pub counts: [u32; 4],
    /// jitter, contrast, brightness, ridged weighted strength.
    pub shape: [f32; 4],
    /// edge width, normal strength, analytic texel delta, unused.
    pub normal: [f32; 4],
    /// seed offset xyz, unused.
    pub seed: [f32; 4],
    /// Per octave: span, frequency, amplitude, LOD weight.
    pub octaves: [[f32; 4]; MAX_OCTAVES],
    /// Per stop: rgb, offset.
    pub ramp: [[f32; 4]; MAX_RAMP_STOPS],
}

impl BakeUniform {
    /// Flatten a spec into the uniform the shader reads.
    pub fn from_spec(spec: &TextureSpec) -> BakeUniform {
        let plan = spec.octave_plan();
        let normal = spec.normal;
        let offset = crate::noise::seed_offset_3d(spec.seed_offset);

        let mut octaves = [[0.0f32; 4]; MAX_OCTAVES];
        for (slot, o) in octaves.iter_mut().zip(&plan) {
            *slot = [o.span, o.freq, o.amplitude, o.weight];
        }

        let mut ramp = [[0.0f32; 4]; MAX_RAMP_STOPS];
        let stops = spec.ramp.len().min(MAX_RAMP_STOPS);
        for (slot, (at, color)) in ramp.iter_mut().zip(&spec.ramp) {
            *slot = [color.x, color.y, color.z, *at];
        }

        // The step the boundary normal differentiates over: a fixed fraction of
        // the tile, so the normal map does not flatten out on a low tier (see
        // `texture::NORMAL_REFERENCE_TEXELS`).
        let base_span = plan.first().map(|o| o.span).unwrap_or(1.0);
        let delta = base_span / crate::texture::NORMAL_REFERENCE_TEXELS;

        BakeUniform {
            mode: [
                match spec.noise.lattice() {
                    crate::noise::Lattice::Cubic => 0,
                    crate::noise::Lattice::Fcc => 1,
                },
                spec.noise.return_type().code(),
                spec.fractal.code(),
                plan.len() as u32,
            ],
            counts: [
                normal.map(|n| n.mode.code()).unwrap_or(0),
                stops as u32,
                0,
                0,
            ],
            shape: [
                spec.noise.jitter(),
                spec.contrast,
                spec.brightness,
                spec.weighted_strength,
            ],
            normal: [
                normal.map(|n| n.edge_width).unwrap_or(0.25),
                normal.map(|n| n.strength).unwrap_or(1.0),
                delta,
                0.0,
            ],
            seed: [offset.x, offset.y, offset.z, 0.0],
            octaves,
            ramp,
        }
    }
}

/// `@group(2) @binding(3)` of the **material** shader: how a texture maps onto
/// the world, plus the whole spec for §7's live path. Restated in `shader.wgsl`.
///
/// One uniform rather than two because `@group(2)`'s layout must not depend on
/// the variant key — the live/baked toggle swaps a *pipeline* and keeps the
/// bind group, which is the property that makes it a per-frame decision instead
/// of a rebuild. A baked-only draw reads [`config`](TextureUniform::config) and
/// ignores the other 352 bytes; that is 368 bytes per resident texture, of
/// which there are two in the port.
///
/// [`field`](TextureUniform::field) is [`BakeUniform`] verbatim — the same
/// bytes the bake pass reads out of *its* `@group(0)`. Sharing the struct is
/// not a coincidence to be tidied away later: it is what guarantees the two
/// modes cannot be fed different numbers for the same spec.
#[repr(C)]
#[derive(Clone, Copy, Debug, Pod, Zeroable)]
pub struct TextureUniform {
    /// x: world units → tile units ([`TextureSpec::world_scale`]), y: triplanar
    /// sharpness, z: anti-tiling on/off, w: octave-0 lattice cells per world
    /// metre.
    ///
    /// `w` is the live path's entire world→noise map, and it is exactly the
    /// bake's: the bake samples octave *i* at `uv · span_i`, `uv` is
    /// `world · world_scale`, so `span_0 · world_scale` is cells per metre and
    /// `freq_i` scales it per octave. Precomputed here for the same reason the
    /// octave plan is — so the shader has no rounding rule of its own.
    pub config: [f32; 4],
    /// x: `log2` of the quantized lacunarity, y:
    /// [`LIVE_LOD_CELL_PIXELS`](crate::texture::LIVE_LOD_CELL_PIXELS), zw: pad.
    pub live: [f32; 4],
    /// xyz: [`TextureSpec::live_seed_offset`], w: pad.
    ///
    /// Not `field.seed`, which the bake wraps and this cannot: folding the
    /// offset into the tile is what makes the live image and the baked image
    /// the *same* image rather than two neighbourhoods of one field. See that
    /// method for the equivalence it leans on.
    pub live_seed: [f32; 4],
    /// The spec itself, in the bake pass's own packing.
    pub field: BakeUniform,
}

impl TextureUniform {
    pub fn from_spec(spec: &TextureSpec) -> TextureUniform {
        let seed = spec.live_seed_offset();
        TextureUniform {
            config: [
                spec.world_scale,
                spec.triplanar_sharpness,
                if spec.anti_tiling { 1.0 } else { 0.0 },
                spec.live_cells_per_metre(),
            ],
            live: [
                spec.log2_lacunarity(),
                crate::texture::LIVE_LOD_CELL_PIXELS,
                0.0,
                0.0,
            ],
            live_seed: [seed.x, seed.y, seed.z, 0.0],
            field: BakeUniform::from_spec(spec),
        }
    }

    /// What an untextured draw binds: a legal block that no shader path reads.
    ///
    /// `config` restates the pre-texture defaults (unit scale, the default
    /// sharpness, anti-tiling off) so that a variant key which sets `TEXTURE`
    /// with no handle degrades to a white 1×1 tap rather than to a divide by
    /// zero, and zero octaves so the live loop — which such a draw never enters
    /// — would terminate immediately if it ever did.
    pub fn inert() -> TextureUniform {
        TextureUniform {
            config: [1.0, 4.0, 0.0, 1.0],
            live: [1.0, crate::texture::LIVE_LOD_CELL_PIXELS, 0.0, 0.0],
            live_seed: [0.0; 4],
            field: BakeUniform::zeroed(),
        }
    }
}

// ---------------------------------------------------------------------------
// The persisted form
// ---------------------------------------------------------------------------

/// The layout version of a stored bake.
///
/// Bumped whenever the *shape* of what a bake produces changes, so that an
/// entry written by an older engine is refused rather than reinterpreted.
/// Version 2 added the mip chain: v1 stored a single level per map, and a v1
/// blob decoded as a v2 one would hand the renderer a texture whose upper
/// levels are whatever the last session's allocator had lying around.
///
/// This is belt and braces — the spec bytes and the per-level lengths would
/// each already reject a v1 entry — but a version field states the intent
/// where a length check only implies it, and it is the field a future change
/// can lean on when the sizes happen to line up.
pub const TEXTURE_DATA_VERSION: u32 = 2;

/// Mip levels a square `resolution` texture carries: the full chain to 1×1.
///
/// `1` for a 1×1 texture (the registry's default white/flat pair), so the
/// no-texture path needs no special case.
pub fn mip_level_count(resolution: u32) -> u32 {
    u32::BITS - resolution.max(1).leading_zeros()
}

/// The edge length of `level` of a `resolution` texture, floored at 1.
pub fn mip_size(resolution: u32, level: u32) -> u32 {
    (resolution >> level.min(31)).max(1)
}

/// One baked texture's raw pixels, as the persistent cache stores them.
///
/// `spec` is the `postcard` encoding of the [`TextureSpec`] this came from, not
/// a description of it: the loader compares those bytes to the spec it is
/// asking for, which is what makes a stale, truncated, colliding or hostile
/// entry fail loudly instead of quietly painting the wrong terrain.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TextureData {
    /// [`TEXTURE_DATA_VERSION`] at the time of writing.
    pub version: u32,
    pub resolution: u32,
    pub spec: Vec<u8>,
    /// The albedo mip chain, level 0 first, each level `size² × 4` bytes of
    /// RGBA8 row-major from the top. Storing the chain rather than
    /// regenerating it on load keeps the cache's contract exact — a warm start
    /// gets the same texels in every level, not merely the same level 0.
    pub albedo: Vec<Vec<u8>>,
    /// Same shape, packed tangent-space normals.
    pub normal: Vec<Vec<u8>>,
}

impl TextureData {
    /// Whether this entry really is a bake of `spec` at `resolution`.
    pub fn matches(&self, spec: &TextureSpec, resolution: u32) -> bool {
        let levels = mip_level_count(resolution) as usize;
        let chain_ok = |chain: &Vec<Vec<u8>>| {
            chain.len() == levels
                && chain.iter().enumerate().all(|(level, pixels)| {
                    let size = mip_size(resolution, level as u32) as usize;
                    pixels.len() == size * size * 4
                })
        };
        self.version == TEXTURE_DATA_VERSION
            && self.resolution == resolution
            && chain_ok(&self.albedo)
            && chain_ok(&self.normal)
            && postcard::to_stdvec(spec).map(|b| b == self.spec).unwrap_or(false)
    }
}

// ---------------------------------------------------------------------------
// The baker
// ---------------------------------------------------------------------------

/// The bake pass's pipelines and its one uniform slot.
///
/// Built once per [`Renderer`](crate::Renderer). Bakes run one at a time and
/// each submits before the next writes the uniform, so a single buffer is
/// enough — there is no frame pipelining to race with.
pub struct TextureBaker {
    albedo: wgpu::RenderPipeline,
    normal: wgpu::RenderPipeline,
    /// Level `i+1` from level `i`: a plain 2×2 box.
    mip_color: wgpu::RenderPipeline,
    /// Same, but unpacking, averaging, renormalizing and repacking.
    mip_normal: wgpu::RenderPipeline,
    mip_layout: wgpu::BindGroupLayout,
    buffer: wgpu::Buffer,
    bind_group: wgpu::BindGroup,
}

impl TextureBaker {
    pub fn new(device: &wgpu::Device) -> TextureBaker {
        let layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("bake params layout"),
            entries: &[wgpu::BindGroupLayoutEntry {
                binding: 0,
                visibility: wgpu::ShaderStages::FRAGMENT,
                ty: wgpu::BindingType::Buffer {
                    ty: wgpu::BufferBindingType::Uniform,
                    has_dynamic_offset: false,
                    min_binding_size: wgpu::BufferSize::new(
                        std::mem::size_of::<BakeUniform>() as u64
                    ),
                },
                count: None,
            }],
        });
        let buffer = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("bake params"),
            size: std::mem::size_of::<BakeUniform>() as u64,
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("bake params bind group"),
            layout: &layout,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: buffer.as_entire_binding(),
            }],
        });

        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("bake pipeline layout"),
            bind_group_layouts: &[Some(&layout)],
            immediate_size: 0,
        });

        // The downsample's own group 0: the level above, and nothing else. It
        // shares `binding: 1` with nothing the bake pass uses, and wgpu checks
        // bindings per entry point, so the two pipelines coexist in one module.
        // No sampler — `fs_mip_*` fetches texels by integer index.
        let mip_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("mip source layout"),
            entries: &[wgpu::BindGroupLayoutEntry {
                binding: 1,
                visibility: wgpu::ShaderStages::FRAGMENT,
                ty: wgpu::BindingType::Texture {
                    sample_type: wgpu::TextureSampleType::Float { filterable: true },
                    view_dimension: wgpu::TextureViewDimension::D2,
                    multisampled: false,
                },
                count: None,
            }],
        });
        let mip_pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("mip pipeline layout"),
            bind_group_layouts: &[Some(&mip_layout)],
            immediate_size: 0,
        });

        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("texture bake"),
            source: wgpu::ShaderSource::Wgsl(bake_shader_source().into()),
        });

        let make_with = |entry: &str, label: &str, pipeline_layout: &wgpu::PipelineLayout| {
            device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
                label: Some(label),
                layout: Some(pipeline_layout),
                vertex: wgpu::VertexState {
                    module: &shader,
                    entry_point: Some("vs_bake"),
                    buffers: &[],
                    compilation_options: Default::default(),
                },
                fragment: Some(wgpu::FragmentState {
                    module: &shader,
                    entry_point: Some(entry),
                    targets: &[Some(wgpu::ColorTargetState {
                        format: BAKE_FORMAT,
                        blend: Some(wgpu::BlendState::REPLACE),
                        write_mask: wgpu::ColorWrites::ALL,
                    })],
                    compilation_options: Default::default(),
                }),
                primitive: wgpu::PrimitiveState {
                    topology: wgpu::PrimitiveTopology::TriangleList,
                    cull_mode: None,
                    ..Default::default()
                },
                depth_stencil: None,
                multisample: wgpu::MultisampleState::default(),
                multiview_mask: None,
                cache: None,
            })
        };
        let make = |entry: &str, label: &str| make_with(entry, label, &pipeline_layout);

        TextureBaker {
            albedo: make("fs_albedo", "bake albedo"),
            normal: make("fs_normal", "bake normal"),
            mip_color: make_with("fs_mip_color", "mip color", &mip_pipeline_layout),
            mip_normal: make_with("fs_mip_normal", "mip normal", &mip_pipeline_layout),
            mip_layout,
            buffer,
            bind_group,
        }
    }

    /// Render `spec` to a fresh (albedo, normal) pair at `resolution`, each with
    /// a full mip chain.
    pub fn bake(
        &self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        spec: &TextureSpec,
        resolution: u32,
    ) -> (wgpu::Texture, wgpu::Texture) {
        queue.write_buffer(
            &self.buffer,
            0,
            bytemuck::bytes_of(&BakeUniform::from_spec(spec)),
        );

        let albedo = create_target(device, resolution, "baked albedo");
        let normal = create_target(device, resolution, "baked normal");

        let mut encoder =
            device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: Some("bake") });
        for (texture, pipeline, label) in [
            (&albedo, &self.albedo, "bake albedo pass"),
            (&normal, &self.normal, "bake normal pass"),
        ] {
            // Level 0 only: the chain below it is filtered from this, not
            // re-evaluated at a lower resolution. Point-sampling the field
            // again at half the density would alias exactly as badly as having
            // no mips at all — the whole job of a mip is to *average* the
            // detail it can no longer resolve.
            let view = mip_view(texture, 0);
            let mut pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some(label),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view: &view,
                    resolve_target: None,
                    ops: wgpu::Operations {
                        // The fullscreen triangle covers every texel, so the
                        // clear only exists to keep the attachment defined.
                        load: wgpu::LoadOp::Clear(wgpu::Color::BLACK),
                        store: wgpu::StoreOp::Store,
                    },
                    depth_slice: None,
                })],
                depth_stencil_attachment: None,
                timestamp_writes: None,
                occlusion_query_set: None,
                multiview_mask: None,
            });
            pass.set_pipeline(pipeline);
            pass.set_bind_group(0, &self.bind_group, &[]);
            pass.draw(0..3, 0..1);
        }

        self.generate_mips(device, &mut encoder, &albedo, resolution, &self.mip_color);
        self.generate_mips(device, &mut encoder, &normal, resolution, &self.mip_normal);

        queue.submit(Some(encoder.finish()));

        (albedo, normal)
    }

    /// Fill levels `1..n` of `texture` from level 0, one render pass each.
    ///
    /// Public so the cache-hit path can rebuild a chain it did not bake, and so
    /// the tests can drive the two filters against a texture they uploaded
    /// themselves.
    pub fn generate_mips(
        &self,
        device: &wgpu::Device,
        encoder: &mut wgpu::CommandEncoder,
        texture: &wgpu::Texture,
        resolution: u32,
        pipeline: &wgpu::RenderPipeline,
    ) {
        for level in 1..mip_level_count(resolution) {
            let source = mip_view(texture, level - 1);
            let target = mip_view(texture, level);
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("mip source"),
                layout: &self.mip_layout,
                entries: &[wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::TextureView(&source),
                }],
            });
            let mut pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some("mip downsample"),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view: &target,
                    resolve_target: None,
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Clear(wgpu::Color::BLACK),
                        store: wgpu::StoreOp::Store,
                    },
                    depth_slice: None,
                })],
                depth_stencil_attachment: None,
                timestamp_writes: None,
                occlusion_query_set: None,
                multiview_mask: None,
            });
            pass.set_pipeline(pipeline);
            pass.set_bind_group(0, &bind_group, &[]);
            pass.draw(0..3, 0..1);
        }
    }

    /// The albedo chain's filter: a plain 2×2 box.
    pub fn mip_color_pipeline(&self) -> &wgpu::RenderPipeline {
        &self.mip_color
    }

    /// The normal chain's filter: 2×2 box in *unpacked* space, renormalized.
    pub fn mip_normal_pipeline(&self) -> &wgpu::RenderPipeline {
        &self.mip_normal
    }
}

/// A view of exactly one mip level — what a downsample reads and what it
/// writes. A default view spans the whole chain, which is right for sampling
/// and wrong for both ends of this pass.
fn mip_view(texture: &wgpu::Texture, level: u32) -> wgpu::TextureView {
    texture.create_view(&wgpu::TextureViewDescriptor {
        label: Some("mip level"),
        base_mip_level: level,
        mip_level_count: Some(1),
        ..Default::default()
    })
}

fn create_target(device: &wgpu::Device, resolution: u32, label: &str) -> wgpu::Texture {
    device.create_texture(&wgpu::TextureDescriptor {
        label: Some(label),
        size: wgpu::Extent3d {
            width: resolution,
            height: resolution,
            depth_or_array_layers: 1,
        },
        // The full chain to 1×1. Every level is a render target (it is filled
        // by a downsample pass) as well as a sampled texture, which is why the
        // usage below carries `RENDER_ATTACHMENT` for the whole texture rather
        // than only for level 0.
        mip_level_count: mip_level_count(resolution),
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: BAKE_FORMAT,
        usage: wgpu::TextureUsages::RENDER_ATTACHMENT
            | wgpu::TextureUsages::TEXTURE_BINDING
            | wgpu::TextureUsages::COPY_SRC
            | wgpu::TextureUsages::COPY_DST,
        view_formats: &[],
    })
}

/// Upload an already-baked mip chain — the cache-hit path, which must land on
/// exactly the texture a cold bake would have produced, *including* the levels
/// a cold bake filtered rather than rendered.
///
/// `levels` is level 0 first. Levels beyond the chain are ignored and missing
/// ones are left undefined, so callers hand over a chain that
/// [`TextureData::matches`] has already vetted.
pub fn upload_target(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    resolution: u32,
    levels: &[Vec<u8>],
    label: &str,
) -> wgpu::Texture {
    let texture = create_target(device, resolution, label);
    for (level, pixels) in levels.iter().enumerate().take(mip_level_count(resolution) as usize) {
        let level = level as u32;
        let size = mip_size(resolution, level);
        queue.write_texture(
            wgpu::TexelCopyTextureInfo {
                mip_level: level,
                ..texture.as_image_copy()
            },
            pixels,
            wgpu::TexelCopyBufferLayout {
                offset: 0,
                bytes_per_row: Some(size * 4),
                rows_per_image: Some(size),
            },
            wgpu::Extent3d {
                width: size,
                height: size,
                depth_or_array_layers: 1,
            },
        );
    }
    texture
}

/// Read one RGBA8 mip level back, tightly packed.
///
/// Blocking: it polls the device until the map callback fires. Only ever called
/// when a [`CacheStore`] said it can persist textures, which the web store does
/// not (there is no blocking poll in a browser).
pub fn read_level(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    texture: &wgpu::Texture,
    resolution: u32,
    level: u32,
) -> Option<Vec<u8>> {
    let size = mip_size(resolution, level);
    let unpadded = size * 4;
    // `copy_texture_to_buffer` wants rows aligned to 256 bytes.
    let padded = unpadded.div_ceil(256) * 256;
    let readback = device.create_buffer(&wgpu::BufferDescriptor {
        label: Some("bake readback"),
        size: (padded as u64) * (size as u64),
        usage: wgpu::BufferUsages::COPY_DST | wgpu::BufferUsages::MAP_READ,
        mapped_at_creation: false,
    });

    let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor {
        label: Some("bake readback"),
    });
    encoder.copy_texture_to_buffer(
        wgpu::TexelCopyTextureInfo {
            mip_level: level,
            ..texture.as_image_copy()
        },
        wgpu::TexelCopyBufferInfo {
            buffer: &readback,
            layout: wgpu::TexelCopyBufferLayout {
                offset: 0,
                bytes_per_row: Some(padded),
                rows_per_image: Some(size),
            },
        },
        wgpu::Extent3d {
            width: size,
            height: size,
            depth_or_array_layers: 1,
        },
    );
    queue.submit(Some(encoder.finish()));

    let (tx, rx) = std::sync::mpsc::channel();
    readback.map_async(wgpu::MapMode::Read, .., move |r| {
        let _ = tx.send(r);
    });
    if device.poll(wgpu::PollType::wait_indefinitely()).is_err() {
        return None;
    }
    rx.recv().ok()?.ok()?;

    let mapped = readback.get_mapped_range(..).ok()?;
    let mut pixels = Vec::with_capacity((unpadded * size) as usize);
    for row in 0..size as usize {
        let start = row * padded as usize;
        pixels.extend_from_slice(&mapped[start..start + unpadded as usize]);
    }
    drop(mapped);
    readback.unmap();
    Some(pixels)
}

/// Read level 0 back — what "the texture" means to everything that does not
/// care about the chain.
pub fn read_target(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    texture: &wgpu::Texture,
    resolution: u32,
) -> Option<Vec<u8>> {
    read_level(device, queue, texture, resolution, 0)
}

/// Read the whole mip chain back, level 0 first — what the cache stores.
pub fn read_chain(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    texture: &wgpu::Texture,
    resolution: u32,
) -> Option<Vec<Vec<u8>>> {
    (0..mip_level_count(resolution))
        .map(|level| read_level(device, queue, texture, resolution, level))
        .collect()
}

// ---------------------------------------------------------------------------
// The GPU registry
// ---------------------------------------------------------------------------

/// One resident baked texture: both maps, their sampling params, and the bind
/// group `@group(2)` of the material shader wants.
pub struct GpuTexture {
    pub albedo: wgpu::Texture,
    pub normal: wgpu::Texture,
    pub params: wgpu::Buffer,
    pub bind_group: wgpu::BindGroup,
}

/// Handle → GPU textures. The texture-side twin of
/// [`MeshRegistry`](crate::registry::MeshRegistry), and content-addressed for
/// the same reason: two materials naming the same spec share one bake.
pub struct TextureRegistry {
    textures: HashMap<TextureHandle, GpuTexture>,
    layout: wgpu::BindGroupLayout,
    sampler: wgpu::Sampler,
    /// What an entity with no texture binds. `@group(2)` is in the pipeline
    /// layout unconditionally — one layout for every variant is simpler than
    /// two and costs an untextured draw one bind-group set that the sort order
    /// already makes near-free — so *something* legal has to be there.
    default_bind_group: wgpu::BindGroup,
    /// Kept alive explicitly rather than relying on the bind group's internal
    /// references: a 1×1 texture costs nothing and an owner that reads as an
    /// owner costs nothing either.
    _default_resources: (wgpu::Texture, wgpu::Texture, wgpu::Buffer),
}

impl TextureRegistry {
    pub fn new(device: &wgpu::Device, queue: &wgpu::Queue) -> TextureRegistry {
        let layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("texture bind layout"),
            entries: &[
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: true },
                        view_dimension: wgpu::TextureViewDimension::D2,
                        multisampled: false,
                    },
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: true },
                        view_dimension: wgpu::TextureViewDimension::D2,
                        multisampled: false,
                    },
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 2,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 3,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: wgpu::BufferSize::new(
                            std::mem::size_of::<TextureUniform>() as u64,
                        ),
                    },
                    count: None,
                },
            ],
        });

        // Repeat, because the bake *is* a tile — a clamped sampler would smear
        // the last texel across a hillside.
        //
        // Trilinear: `Linear` between levels as well as within one. `Nearest`
        // between levels is a visible seam in the middle of a hillside — the
        // band where the LOD flips is a hard edge in sharpness — and the
        // difference costs one extra bilinear fetch that every part shipping
        // since 2005 does in fixed function.
        //
        // No anisotropy, deliberately: the anti-tiling sampler already spends
        // nine taps per plane and three planes per fragment, and multiplying
        // that by an anisotropic tap count is exactly the fragment cost DESIGN
        // §7's whole bake-vs-live argument exists to avoid. The cost is some
        // blur on ground planes at grazing angles, which is the standard
        // trilinear trade.
        let sampler = device.create_sampler(&wgpu::SamplerDescriptor {
            label: Some("baked texture sampler"),
            address_mode_u: wgpu::AddressMode::Repeat,
            address_mode_v: wgpu::AddressMode::Repeat,
            address_mode_w: wgpu::AddressMode::Repeat,
            mag_filter: wgpu::FilterMode::Linear,
            min_filter: wgpu::FilterMode::Linear,
            mipmap_filter: wgpu::MipmapFilterMode::Linear,
            ..Default::default()
        });

        // 1×1 white albedo and 1×1 flat normal: an untextured material's
        // sampling multiplies by white and perturbs the normal by nothing, so
        // the bit-unset path is *provably* the pre-texture look. A 1×1 texture
        // has exactly one mip level, so the chain needs no special case here.
        let white = upload_target(
            device,
            queue,
            1,
            std::slice::from_ref(&vec![255, 255, 255, 255]),
            "default albedo",
        );
        let flat = upload_target(
            device,
            queue,
            1,
            std::slice::from_ref(&vec![128, 128, 255, 255]),
            "default normal",
        );
        let default_params = create_params(device, queue, &TextureUniform::inert());
        let default_bind_group = create_bind_group(
            device,
            &layout,
            &sampler,
            &white,
            &flat,
            &default_params,
            "default texture bind group",
        );

        TextureRegistry {
            textures: HashMap::new(),
            layout,
            sampler,
            default_bind_group,
            _default_resources: (white, flat, default_params),
        }
    }

    /// The `@group(2)` layout the render pipelines are built against.
    pub fn layout(&self) -> &wgpu::BindGroupLayout {
        &self.layout
    }

    /// What an untextured draw binds.
    pub fn default_bind_group(&self) -> &wgpu::BindGroup {
        &self.default_bind_group
    }

    pub fn get(&self, handle: TextureHandle) -> Option<&GpuTexture> {
        self.textures.get(&handle)
    }

    pub fn contains(&self, handle: TextureHandle) -> bool {
        self.textures.contains_key(&handle)
    }

    pub fn len(&self) -> usize {
        self.textures.len()
    }

    pub fn is_empty(&self) -> bool {
        self.textures.is_empty()
    }

    /// Make `handle` resident from raw RGBA8 pixels the caller already has —
    /// the [`UiAtlasImage`](crate::ui::UiAtlasImage) path, and the only way
    /// into this registry that does not go through a
    /// [`TextureSpec`](crate::texture::TextureSpec).
    ///
    /// Idempotent: a handle that is already resident is left exactly alone, so
    /// a host may call this every frame and pay one hash lookup.
    ///
    /// Unlike [`resolve`](TextureRegistry::resolve) this is **not** square, has
    /// **no mip chain** and touches **no cache**. All three are the same
    /// decision: the images that come in this way are HUD atlases sampled at
    /// their own texel size by a nearest sampler, so a chain would be dead
    /// memory, a square would be wasted memory, and a store entry would be a
    /// cache of something the game rebuilt in a microsecond anyway.
    ///
    /// The normal map is the registry's own flat 1×1, so the resulting
    /// [`GpuTexture`] is complete enough for the ordinary material path too —
    /// which is what would let a game put an icon on a world-space quad without
    /// a second mechanism, if one ever wanted to.
    pub fn insert_image(
        &mut self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        handle: TextureHandle,
        width: u32,
        height: u32,
        rgba: &[u8],
    ) {
        if self.textures.contains_key(&handle) {
            return;
        }
        let expected = (width as usize) * (height as usize) * 4;
        if width == 0 || height == 0 || rgba.len() != expected {
            log::warn!(
                "runt-ui: image {:#018x} is {width}×{height} but carries {} bytes (wanted \
                 {expected}); not uploaded",
                handle.0,
                rgba.len()
            );
            return;
        }

        let size = wgpu::Extent3d {
            width,
            height,
            depth_or_array_layers: 1,
        };
        let albedo = device.create_texture(&wgpu::TextureDescriptor {
            label: Some("ui atlas image"),
            size,
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: BAKE_FORMAT,
            usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
            view_formats: &[],
        });
        queue.write_texture(
            albedo.as_image_copy(),
            rgba,
            wgpu::TexelCopyBufferLayout {
                offset: 0,
                bytes_per_row: Some(width * 4),
                rows_per_image: Some(height),
            },
            size,
        );

        // A flat normal and an inert params block, so the entry is a complete
        // `GpuTexture` and the material path cannot trip over it. The same 1×1
        // `(128, 128, 255)` texel `new` builds for untextured materials, and for
        // the same reason: perturbing the normal by nothing.
        let normal = upload_target(
            device,
            queue,
            1,
            std::slice::from_ref(&vec![128, 128, 255, 255]),
            "ui atlas normal",
        );
        let params = create_params(device, queue, &TextureUniform::inert());
        let bind_group = create_bind_group(
            device,
            &self.layout,
            &self.sampler,
            &albedo,
            &normal,
            &params,
            "ui atlas bind group",
        );
        log::info!("runt-ui: atlas {:#018x} uploaded ({width}×{height})", handle.0);
        self.textures.insert(
            handle,
            GpuTexture {
                albedo,
                normal,
                params,
                bind_group,
            },
        );
    }

    /// Resolve `spec` at `resolution` to a resident texture, in this order:
    ///
    /// 1. **Memory.** Already baked this session → nothing happens.
    /// 2. **Store.** A validated entry → upload its pixels, no bake.
    /// 3. **Cold.** Run the bake pass, and write the pixels back if the store
    ///    can hold them.
    ///
    /// Every path returns the same handle and the same pixels, so a caller
    /// cannot tell which one ran.
    pub fn resolve(
        &mut self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        baker: &TextureBaker,
        spec: &TextureSpec,
        resolution: u32,
        store: &dyn CacheStore,
    ) -> TextureHandle {
        let handle = TextureHandle(spec.content_key(resolution));
        if self.textures.contains_key(&handle) {
            return handle;
        }

        let (albedo, normal) = match store.load_texture(handle.0) {
            Some(data) if data.matches(spec, resolution) => (
                upload_target(device, queue, resolution, &data.albedo, "cached albedo"),
                upload_target(device, queue, resolution, &data.normal, "cached normal"),
            ),
            other => {
                if other.is_some() {
                    log::warn!(
                        "runt-cache: texture {:#018x} does not match the spec it is filed \
                         under; discarding and rebaking",
                        handle.0
                    );
                }
                let (albedo, normal) = baker.bake(device, queue, spec, resolution);
                if store.caches_textures() {
                    if let (Some(a), Some(n)) = (
                        read_chain(device, queue, &albedo, resolution),
                        read_chain(device, queue, &normal, resolution),
                    ) {
                        store.store_texture(
                            handle.0,
                            &TextureData {
                                version: TEXTURE_DATA_VERSION,
                                resolution,
                                spec: postcard::to_stdvec(spec).unwrap_or_default(),
                                albedo: a,
                                normal: n,
                            },
                        );
                    }
                }
                (albedo, normal)
            }
        };

        let params = create_params(device, queue, &TextureUniform::from_spec(spec));
        let bind_group = create_bind_group(
            device,
            &self.layout,
            &self.sampler,
            &albedo,
            &normal,
            &params,
            "baked texture bind group",
        );
        self.textures.insert(
            handle,
            GpuTexture {
                albedo,
                normal,
                params,
                bind_group,
            },
        );
        handle
    }
}

/// The per-texture uniform ([`TextureUniform`]), uploaded once per resident
/// texture.
///
/// It lives with the *texture*, not the instance, because it describes how this
/// spec maps onto the world — two entities wearing the same grass want the same
/// tiling whether or not anyone remembered to copy a number — and because §7's
/// live path needs the whole spec here, where it is written once per bake
/// rather than once per draw.
fn create_params(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    uniform: &TextureUniform,
) -> wgpu::Buffer {
    let buffer = device.create_buffer(&wgpu::BufferDescriptor {
        label: Some("texture params"),
        size: std::mem::size_of::<TextureUniform>() as u64,
        usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
        mapped_at_creation: false,
    });
    queue.write_buffer(&buffer, 0, bytemuck::bytes_of(uniform));
    buffer
}

fn create_bind_group(
    device: &wgpu::Device,
    layout: &wgpu::BindGroupLayout,
    sampler: &wgpu::Sampler,
    albedo: &wgpu::Texture,
    normal: &wgpu::Texture,
    params: &wgpu::Buffer,
    label: &str,
) -> wgpu::BindGroup {
    let albedo_view = albedo.create_view(&wgpu::TextureViewDescriptor::default());
    let normal_view = normal.create_view(&wgpu::TextureViewDescriptor::default());
    device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some(label),
        layout,
        entries: &[
            wgpu::BindGroupEntry {
                binding: 0,
                resource: wgpu::BindingResource::TextureView(&albedo_view),
            },
            wgpu::BindGroupEntry {
                binding: 1,
                resource: wgpu::BindingResource::TextureView(&normal_view),
            },
            wgpu::BindGroupEntry {
                binding: 2,
                resource: wgpu::BindingResource::Sampler(sampler),
            },
            wgpu::BindGroupEntry {
                binding: 3,
                resource: params.as_entire_binding(),
            },
        ],
    })
}
