//! Baking a [`TextureSpec`] to GPU textures (DESIGN §7's baked path).
//!
//! > *Baked (baseline): rendered once to an RGBA8 texture at tier-scaled
//! > resolution at load time. This is a fragment pass, not compute — it works
//! > fully within WebGL2 limits (bake resolution capped at 2048² there).* — §7
//!
//! One spec produces **two** targets, from one octave loop:
//!
//! ```text
//!   TextureSpec ──► vs_bake (fullscreen triangle)
//!                     ├─ fs_albedo ─► RGBA8, ramp-mapped colour
//!                     └─ fs_normal ─► RGBA8, packed Voronoi-boundary normal
//! ```
//!
//! Two single-target passes rather than one MRT pass: two colour attachments
//! would also fit `downlevel_webgl2_defaults`, but a single attachment is the
//! shape every backend agrees on without thinking about it, and this is
//! load-time work the content cache mostly skips.
//!
//! ## Caching (DESIGN §6's invariant, applied one level down)
//!
//! Layered exactly like the mesh cache, and under the same rule: **the cache is
//! purely an optimization; deleting it must not change a pixel.**
//!
//! ```text
//!   TextureHandle (= content_key)
//!        ├─ in memory  → TextureRegistry: handle → GPU textures + bind group
//!        └─ persistent → CacheStore::load_texture: handle → raw RGBA8 bytes
//! ```
//!
//! A store entry is untrusted: it carries the `postcard` bytes of the spec it
//! was baked from and its resolution, and anything that does not match exactly
//! — wrong size, stale layout, key collision, hostile file — is discarded and
//! rebaked. `tests/texture_cache.rs` runs cold, warm and deleted-mid-run and
//! demands byte-identical pixels from all three.
//!
//! Reading pixels back off the GPU needs a blocking device poll, which is not
//! available on the web. Stores therefore opt in with
//! [`CacheStore::caches_textures`]; the default is `false`, so the web's
//! [`NoopCache`](crate::cache::NoopCache) path never tries.

use std::collections::HashMap;

use bytemuck::{Pod, Zeroable};
use serde::{Deserialize, Serialize};

use crate::cache::CacheStore;
use crate::texture::{TextureHandle, TextureSpec, MAX_OCTAVES, MAX_RAMP_STOPS};

/// The noise library, shared with any future live-eval variant.
pub const NOISE_SHADER: &str = include_str!("noise.wgsl");

/// The bake pass. Not standalone — see [`bake_shader_source`].
pub const BAKE_SHADER: &str = include_str!("bake.wgsl");

/// Both baked targets are RGBA8. Not sRGB: runt has no colour management, so a
/// baked albedo is in exactly the space `Material::base_color` is in, and the
/// normal target must be linear regardless.
pub const BAKE_FORMAT: wgpu::TextureFormat = wgpu::TextureFormat::Rgba8Unorm;

/// The bake shader, with the noise library prepended.
///
/// The dumbest possible include, matching
/// [`material::variant_source`](crate::material::variant_source)'s philosophy:
/// no `#include` grammar, no token scanning, just a concatenation — so both
/// files stay ordinary readable WGSL.
pub fn bake_shader_source() -> String {
    let mut out = String::with_capacity(NOISE_SHADER.len() + BAKE_SHADER.len() + 64);
    out.push_str("// generated by runt_core::bake::bake_shader_source\n");
    out.push_str(NOISE_SHADER);
    out.push('\n');
    out.push_str(BAKE_SHADER);
    out
}

// ---------------------------------------------------------------------------
// The uniform
// ---------------------------------------------------------------------------

/// `@group(0)` of the bake pass. Field order is restated in `bake.wgsl`.
///
/// The octave table is *planned on the CPU* ([`TextureSpec::octave_plan`]), so
/// the shader contains no `pow`, no rounding rule and no lattice-period
/// arithmetic it could get subtly different from the Rust twin.
#[repr(C)]
#[derive(Clone, Copy, Debug, Pod, Zeroable)]
pub struct BakeUniform {
    /// lattice, cell return type, fractal, octave count.
    pub mode: [u32; 4],
    /// normal mode, ramp stop count, unused, unused.
    pub counts: [u32; 4],
    /// jitter, contrast, brightness, ridged weighted strength.
    pub shape: [f32; 4],
    /// edge width, normal strength, analytic texel delta, unused.
    pub normal: [f32; 4],
    /// seed offset xyz, unused.
    pub seed: [f32; 4],
    /// Per octave: span, frequency, amplitude, LOD weight.
    pub octaves: [[f32; 4]; MAX_OCTAVES],
    /// Per stop: rgb, offset.
    pub ramp: [[f32; 4]; MAX_RAMP_STOPS],
}

impl BakeUniform {
    /// Flatten a spec into the uniform the shader reads.
    pub fn from_spec(spec: &TextureSpec) -> BakeUniform {
        let plan = spec.octave_plan();
        let normal = spec.normal;
        let offset = crate::noise::seed_offset_3d(spec.seed_offset);

        let mut octaves = [[0.0f32; 4]; MAX_OCTAVES];
        for (slot, o) in octaves.iter_mut().zip(&plan) {
            *slot = [o.span, o.freq, o.amplitude, o.weight];
        }

        let mut ramp = [[0.0f32; 4]; MAX_RAMP_STOPS];
        let stops = spec.ramp.len().min(MAX_RAMP_STOPS);
        for (slot, (at, color)) in ramp.iter_mut().zip(&spec.ramp) {
            *slot = [color.x, color.y, color.z, *at];
        }

        // The step the boundary normal differentiates over: a fixed fraction of
        // the tile, so the normal map does not flatten out on a low tier (see
        // `texture::NORMAL_REFERENCE_TEXELS`).
        let base_span = plan.first().map(|o| o.span).unwrap_or(1.0);
        let delta = base_span / crate::texture::NORMAL_REFERENCE_TEXELS;

        BakeUniform {
            mode: [
                match spec.noise.lattice() {
                    crate::noise::Lattice::Cubic => 0,
                    crate::noise::Lattice::Fcc => 1,
                },
                spec.noise.return_type().code(),
                spec.fractal.code(),
                plan.len() as u32,
            ],
            counts: [
                normal.map(|n| n.mode.code()).unwrap_or(0),
                stops as u32,
                0,
                0,
            ],
            shape: [
                spec.noise.jitter(),
                spec.contrast,
                spec.brightness,
                spec.weighted_strength,
            ],
            normal: [
                normal.map(|n| n.edge_width).unwrap_or(0.25),
                normal.map(|n| n.strength).unwrap_or(1.0),
                delta,
                0.0,
            ],
            seed: [offset.x, offset.y, offset.z, 0.0],
            octaves,
            ramp,
        }
    }
}

// ---------------------------------------------------------------------------
// The persisted form
// ---------------------------------------------------------------------------

/// One baked texture's raw pixels, as the persistent cache stores them.
///
/// `spec` is the `postcard` encoding of the [`TextureSpec`] this came from, not
/// a description of it: the loader compares those bytes to the spec it is
/// asking for, which is what makes a stale, truncated, colliding or hostile
/// entry fail loudly instead of quietly painting the wrong terrain.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TextureData {
    pub resolution: u32,
    pub spec: Vec<u8>,
    /// `resolution² × 4` bytes, RGBA8, row-major from the top.
    pub albedo: Vec<u8>,
    /// Same shape, packed tangent-space normals.
    pub normal: Vec<u8>,
}

impl TextureData {
    /// Whether this entry really is a bake of `spec` at `resolution`.
    pub fn matches(&self, spec: &TextureSpec, resolution: u32) -> bool {
        let expected = (resolution as usize) * (resolution as usize) * 4;
        self.resolution == resolution
            && self.albedo.len() == expected
            && self.normal.len() == expected
            && postcard::to_stdvec(spec).map(|b| b == self.spec).unwrap_or(false)
    }
}

// ---------------------------------------------------------------------------
// The baker
// ---------------------------------------------------------------------------

/// The bake pass's pipelines and its one uniform slot.
///
/// Built once per [`Renderer`](crate::Renderer). Bakes run one at a time and
/// each submits before the next writes the uniform, so a single buffer is
/// enough — there is no frame pipelining to race with.
pub struct TextureBaker {
    albedo: wgpu::RenderPipeline,
    normal: wgpu::RenderPipeline,
    buffer: wgpu::Buffer,
    bind_group: wgpu::BindGroup,
}

impl TextureBaker {
    pub fn new(device: &wgpu::Device) -> TextureBaker {
        let layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("bake params layout"),
            entries: &[wgpu::BindGroupLayoutEntry {
                binding: 0,
                visibility: wgpu::ShaderStages::FRAGMENT,
                ty: wgpu::BindingType::Buffer {
                    ty: wgpu::BufferBindingType::Uniform,
                    has_dynamic_offset: false,
                    min_binding_size: wgpu::BufferSize::new(
                        std::mem::size_of::<BakeUniform>() as u64
                    ),
                },
                count: None,
            }],
        });
        let buffer = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("bake params"),
            size: std::mem::size_of::<BakeUniform>() as u64,
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("bake params bind group"),
            layout: &layout,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: buffer.as_entire_binding(),
            }],
        });

        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("bake pipeline layout"),
            bind_group_layouts: &[Some(&layout)],
            immediate_size: 0,
        });
        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("texture bake"),
            source: wgpu::ShaderSource::Wgsl(bake_shader_source().into()),
        });

        let make = |entry: &str, label: &str| {
            device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
                label: Some(label),
                layout: Some(&pipeline_layout),
                vertex: wgpu::VertexState {
                    module: &shader,
                    entry_point: Some("vs_bake"),
                    buffers: &[],
                    compilation_options: Default::default(),
                },
                fragment: Some(wgpu::FragmentState {
                    module: &shader,
                    entry_point: Some(entry),
                    targets: &[Some(wgpu::ColorTargetState {
                        format: BAKE_FORMAT,
                        blend: Some(wgpu::BlendState::REPLACE),
                        write_mask: wgpu::ColorWrites::ALL,
                    })],
                    compilation_options: Default::default(),
                }),
                primitive: wgpu::PrimitiveState {
                    topology: wgpu::PrimitiveTopology::TriangleList,
                    cull_mode: None,
                    ..Default::default()
                },
                depth_stencil: None,
                multisample: wgpu::MultisampleState::default(),
                multiview_mask: None,
                cache: None,
            })
        };

        TextureBaker {
            albedo: make("fs_albedo", "bake albedo"),
            normal: make("fs_normal", "bake normal"),
            buffer,
            bind_group,
        }
    }

    /// Render `spec` to a fresh (albedo, normal) pair at `resolution`.
    pub fn bake(
        &self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        spec: &TextureSpec,
        resolution: u32,
    ) -> (wgpu::Texture, wgpu::Texture) {
        queue.write_buffer(
            &self.buffer,
            0,
            bytemuck::bytes_of(&BakeUniform::from_spec(spec)),
        );

        let albedo = create_target(device, resolution, "baked albedo");
        let normal = create_target(device, resolution, "baked normal");

        let mut encoder =
            device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: Some("bake") });
        for (texture, pipeline, label) in [
            (&albedo, &self.albedo, "bake albedo pass"),
            (&normal, &self.normal, "bake normal pass"),
        ] {
            let view = texture.create_view(&wgpu::TextureViewDescriptor::default());
            let mut pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some(label),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view: &view,
                    resolve_target: None,
                    ops: wgpu::Operations {
                        // The fullscreen triangle covers every texel, so the
                        // clear only exists to keep the attachment defined.
                        load: wgpu::LoadOp::Clear(wgpu::Color::BLACK),
                        store: wgpu::StoreOp::Store,
                    },
                    depth_slice: None,
                })],
                depth_stencil_attachment: None,
                timestamp_writes: None,
                occlusion_query_set: None,
                multiview_mask: None,
            });
            pass.set_pipeline(pipeline);
            pass.set_bind_group(0, &self.bind_group, &[]);
            pass.draw(0..3, 0..1);
        }
        queue.submit(Some(encoder.finish()));

        (albedo, normal)
    }
}

fn create_target(device: &wgpu::Device, resolution: u32, label: &str) -> wgpu::Texture {
    device.create_texture(&wgpu::TextureDescriptor {
        label: Some(label),
        size: wgpu::Extent3d {
            width: resolution,
            height: resolution,
            depth_or_array_layers: 1,
        },
        // One level. Mipmaps would want a downsample chain and the anti-tiling
        // sampler would want `textureSampleGrad` to keep them correct; both are
        // future work, and the material samples at an explicit LOD 0 so nothing
        // silently reads a level that is not there.
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: BAKE_FORMAT,
        usage: wgpu::TextureUsages::RENDER_ATTACHMENT
            | wgpu::TextureUsages::TEXTURE_BINDING
            | wgpu::TextureUsages::COPY_SRC
            | wgpu::TextureUsages::COPY_DST,
        view_formats: &[],
    })
}

/// Upload already-baked pixels — the cache-hit path, which must land on exactly
/// the texture a cold bake would have produced.
pub fn upload_target(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    resolution: u32,
    pixels: &[u8],
    label: &str,
) -> wgpu::Texture {
    let texture = create_target(device, resolution, label);
    queue.write_texture(
        texture.as_image_copy(),
        pixels,
        wgpu::TexelCopyBufferLayout {
            offset: 0,
            bytes_per_row: Some(resolution * 4),
            rows_per_image: Some(resolution),
        },
        wgpu::Extent3d {
            width: resolution,
            height: resolution,
            depth_or_array_layers: 1,
        },
    );
    texture
}

/// Read an RGBA8 texture back, tightly packed.
///
/// Blocking: it polls the device until the map callback fires. Only ever called
/// when a [`CacheStore`] said it can persist textures, which the web store does
/// not (there is no blocking poll in a browser).
pub fn read_target(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    texture: &wgpu::Texture,
    resolution: u32,
) -> Option<Vec<u8>> {
    let unpadded = resolution * 4;
    // `copy_texture_to_buffer` wants rows aligned to 256 bytes.
    let padded = unpadded.div_ceil(256) * 256;
    let readback = device.create_buffer(&wgpu::BufferDescriptor {
        label: Some("bake readback"),
        size: (padded as u64) * (resolution as u64),
        usage: wgpu::BufferUsages::COPY_DST | wgpu::BufferUsages::MAP_READ,
        mapped_at_creation: false,
    });

    let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor {
        label: Some("bake readback"),
    });
    encoder.copy_texture_to_buffer(
        texture.as_image_copy(),
        wgpu::TexelCopyBufferInfo {
            buffer: &readback,
            layout: wgpu::TexelCopyBufferLayout {
                offset: 0,
                bytes_per_row: Some(padded),
                rows_per_image: Some(resolution),
            },
        },
        wgpu::Extent3d {
            width: resolution,
            height: resolution,
            depth_or_array_layers: 1,
        },
    );
    queue.submit(Some(encoder.finish()));

    let (tx, rx) = std::sync::mpsc::channel();
    readback.map_async(wgpu::MapMode::Read, .., move |r| {
        let _ = tx.send(r);
    });
    if device.poll(wgpu::PollType::wait_indefinitely()).is_err() {
        return None;
    }
    rx.recv().ok()?.ok()?;

    let mapped = readback.get_mapped_range(..).ok()?;
    let mut pixels = Vec::with_capacity((unpadded * resolution) as usize);
    for row in 0..resolution as usize {
        let start = row * padded as usize;
        pixels.extend_from_slice(&mapped[start..start + unpadded as usize]);
    }
    drop(mapped);
    readback.unmap();
    Some(pixels)
}

// ---------------------------------------------------------------------------
// The GPU registry
// ---------------------------------------------------------------------------

/// One resident baked texture: both maps, their sampling params, and the bind
/// group `@group(2)` of the material shader wants.
pub struct GpuTexture {
    pub albedo: wgpu::Texture,
    pub normal: wgpu::Texture,
    pub params: wgpu::Buffer,
    pub bind_group: wgpu::BindGroup,
}

/// Handle → GPU textures. The texture-side twin of
/// [`MeshRegistry`](crate::registry::MeshRegistry), and content-addressed for
/// the same reason: two materials naming the same spec share one bake.
pub struct TextureRegistry {
    textures: HashMap<TextureHandle, GpuTexture>,
    layout: wgpu::BindGroupLayout,
    sampler: wgpu::Sampler,
    /// What an entity with no texture binds. `@group(2)` is in the pipeline
    /// layout unconditionally — one layout for every variant is simpler than
    /// two and costs an untextured draw one bind-group set that the sort order
    /// already makes near-free — so *something* legal has to be there.
    default_bind_group: wgpu::BindGroup,
    /// Kept alive explicitly rather than relying on the bind group's internal
    /// references: a 1×1 texture costs nothing and an owner that reads as an
    /// owner costs nothing either.
    _default_resources: (wgpu::Texture, wgpu::Texture, wgpu::Buffer),
}

impl TextureRegistry {
    pub fn new(device: &wgpu::Device, queue: &wgpu::Queue) -> TextureRegistry {
        let layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("texture bind layout"),
            entries: &[
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: true },
                        view_dimension: wgpu::TextureViewDimension::D2,
                        multisampled: false,
                    },
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: true },
                        view_dimension: wgpu::TextureViewDimension::D2,
                        multisampled: false,
                    },
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 2,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 3,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: wgpu::BufferSize::new(16),
                    },
                    count: None,
                },
            ],
        });

        // Repeat, because the bake *is* a tile — a clamped sampler would smear
        // the last texel across a hillside.
        let sampler = device.create_sampler(&wgpu::SamplerDescriptor {
            label: Some("baked texture sampler"),
            address_mode_u: wgpu::AddressMode::Repeat,
            address_mode_v: wgpu::AddressMode::Repeat,
            address_mode_w: wgpu::AddressMode::Repeat,
            mag_filter: wgpu::FilterMode::Linear,
            min_filter: wgpu::FilterMode::Linear,
            mipmap_filter: wgpu::MipmapFilterMode::Nearest,
            ..Default::default()
        });

        // 1×1 white albedo and 1×1 flat normal: an untextured material's
        // sampling multiplies by white and perturbs the normal by nothing, so
        // the bit-unset path is *provably* the pre-texture look.
        let white = upload_target(device, queue, 1, &[255, 255, 255, 255], "default albedo");
        let flat = upload_target(device, queue, 1, &[128, 128, 255, 255], "default normal");
        let default_params = create_params(device, queue, 1.0, 4.0, false);
        let default_bind_group = create_bind_group(
            device,
            &layout,
            &sampler,
            &white,
            &flat,
            &default_params,
            "default texture bind group",
        );

        TextureRegistry {
            textures: HashMap::new(),
            layout,
            sampler,
            default_bind_group,
            _default_resources: (white, flat, default_params),
        }
    }

    /// The `@group(2)` layout the render pipelines are built against.
    pub fn layout(&self) -> &wgpu::BindGroupLayout {
        &self.layout
    }

    /// What an untextured draw binds.
    pub fn default_bind_group(&self) -> &wgpu::BindGroup {
        &self.default_bind_group
    }

    pub fn get(&self, handle: TextureHandle) -> Option<&GpuTexture> {
        self.textures.get(&handle)
    }

    pub fn contains(&self, handle: TextureHandle) -> bool {
        self.textures.contains_key(&handle)
    }

    pub fn len(&self) -> usize {
        self.textures.len()
    }

    pub fn is_empty(&self) -> bool {
        self.textures.is_empty()
    }

    /// Resolve `spec` at `resolution` to a resident texture, in this order:
    ///
    /// 1. **Memory.** Already baked this session → nothing happens.
    /// 2. **Store.** A validated entry → upload its pixels, no bake.
    /// 3. **Cold.** Run the bake pass, and write the pixels back if the store
    ///    can hold them.
    ///
    /// Every path returns the same handle and the same pixels, so a caller
    /// cannot tell which one ran.
    pub fn resolve(
        &mut self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        baker: &TextureBaker,
        spec: &TextureSpec,
        resolution: u32,
        store: &dyn CacheStore,
    ) -> TextureHandle {
        let handle = TextureHandle(spec.content_key(resolution));
        if self.textures.contains_key(&handle) {
            return handle;
        }

        let (albedo, normal) = match store.load_texture(handle.0) {
            Some(data) if data.matches(spec, resolution) => (
                upload_target(device, queue, resolution, &data.albedo, "cached albedo"),
                upload_target(device, queue, resolution, &data.normal, "cached normal"),
            ),
            other => {
                if other.is_some() {
                    log::warn!(
                        "runt-cache: texture {:#018x} does not match the spec it is filed \
                         under; discarding and rebaking",
                        handle.0
                    );
                }
                let (albedo, normal) = baker.bake(device, queue, spec, resolution);
                if store.caches_textures() {
                    if let (Some(a), Some(n)) = (
                        read_target(device, queue, &albedo, resolution),
                        read_target(device, queue, &normal, resolution),
                    ) {
                        store.store_texture(
                            handle.0,
                            &TextureData {
                                resolution,
                                spec: postcard::to_stdvec(spec).unwrap_or_default(),
                                albedo: a,
                                normal: n,
                            },
                        );
                    }
                }
                (albedo, normal)
            }
        };

        let params = create_params(
            device,
            queue,
            spec.world_scale,
            spec.triplanar_sharpness,
            spec.anti_tiling,
        );
        let bind_group = create_bind_group(
            device,
            &self.layout,
            &self.sampler,
            &albedo,
            &normal,
            &params,
            "baked texture bind group",
        );
        self.textures.insert(
            handle,
            GpuTexture {
                albedo,
                normal,
                params,
                bind_group,
            },
        );
        handle
    }
}

/// The per-texture sampling params: `(world_scale, sharpness, anti-tiling, 0)`.
///
/// They live with the *texture*, not the instance, because they describe how
/// this bake maps onto the world — two entities wearing the same grass want the
/// same tiling whether or not anyone remembered to copy a number.
fn create_params(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    world_scale: f32,
    sharpness: f32,
    anti_tiling: bool,
) -> wgpu::Buffer {
    let buffer = device.create_buffer(&wgpu::BufferDescriptor {
        label: Some("texture params"),
        size: 16,
        usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
        mapped_at_creation: false,
    });
    let values: [f32; 4] = [
        world_scale,
        sharpness,
        if anti_tiling { 1.0 } else { 0.0 },
        0.0,
    ];
    queue.write_buffer(&buffer, 0, bytemuck::bytes_of(&values));
    buffer
}

fn create_bind_group(
    device: &wgpu::Device,
    layout: &wgpu::BindGroupLayout,
    sampler: &wgpu::Sampler,
    albedo: &wgpu::Texture,
    normal: &wgpu::Texture,
    params: &wgpu::Buffer,
    label: &str,
) -> wgpu::BindGroup {
    let albedo_view = albedo.create_view(&wgpu::TextureViewDescriptor::default());
    let normal_view = normal.create_view(&wgpu::TextureViewDescriptor::default());
    device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some(label),
        layout,
        entries: &[
            wgpu::BindGroupEntry {
                binding: 0,
                resource: wgpu::BindingResource::TextureView(&albedo_view),
            },
            wgpu::BindGroupEntry {
                binding: 1,
                resource: wgpu::BindingResource::TextureView(&normal_view),
            },
            wgpu::BindGroupEntry {
                binding: 2,
                resource: wgpu::BindingResource::Sampler(sampler),
            },
            wgpu::BindGroupEntry {
                binding: 3,
                resource: params.as_entire_binding(),
            },
        ],
    })
}
