//! Materials and shader variants (DESIGN §5).
//!
//! A material is two things: a small uniform block (base color now, ramp params
//! later) and a *variant key* — a bitflag set naming the features its shader
//! needs. One WGSL source covers every variant; [`variant_source`] prepends the
//! feature `const`s and the compiler folds the dead branches away.
//!
//! Adding a new look is therefore a new flag plus a branch in the shader, never
//! a new pipeline architecture. The renderer caches one pipeline per key and
//! the draw list sorts by key, so a variant costs one state change per frame at
//! worst.

use bevy_ecs::prelude::Component;
use glam::Vec4;

use crate::texture::TextureHandle;

/// The un-preprocessed shader. Not valid WGSL on its own — the feature `const`s
/// it branches on are prepended by [`variant_source`].
pub const BASE_SHADER: &str = include_str!("shader.wgsl");

/// Shader feature bits.
///
/// `VERTEX_COLOR`, `TEXTURE` and `NORMAL_MAP` are implemented; `RAMP` and
/// `LIVE_TEX` are reserved so that the key space (and every cache built on it)
/// is stable when they land.
///
/// **Bit positions are permanent.** `NORMAL_MAP` is appended at bit 4 rather
/// than slotted in beside `TEXTURE` for exactly that reason: renumbering would
/// silently re-key every pipeline cache and every scene that spells a variant
/// out. New looks append.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct MaterialVariant(u32);

impl MaterialVariant {
    /// No features: flat `base_color`, hemisphere + key light only.
    pub const NONE: MaterialVariant = MaterialVariant(0);
    /// Multiply albedo by the mesh's per-vertex color.
    pub const VERTEX_COLOR: MaterialVariant = MaterialVariant(1 << 0);
    /// Sample a baked procedural texture (§7), triplanar in world space.
    pub const TEXTURE: MaterialVariant = MaterialVariant(1 << 1);
    /// Reserved (§5): toon/ramp remap of the key-light term.
    pub const RAMP: MaterialVariant = MaterialVariant(1 << 2);
    /// Reserved (§7): evaluate the procedural texture live in the fragment
    /// shader instead of sampling a bake.
    pub const LIVE_TEX: MaterialVariant = MaterialVariant(1 << 3);
    /// Perturb the shading normal with the bake's normal map (§7).
    ///
    /// Separate from [`TEXTURE`](MaterialVariant::TEXTURE) rather than implied
    /// by it: the crinkle is the expensive half (three more taps and a
    /// re-normalize) and plenty of surfaces want the colour without it. It is
    /// inert on its own — with no texture bound there is nothing to perturb by.
    pub const NORMAL_MAP: MaterialVariant = MaterialVariant(1 << 4);

    /// Every declared flag, with the WGSL `const` it maps to. The order here is
    /// the order the preprocessor emits, so generated sources are stable.
    pub const FLAGS: [(&'static str, MaterialVariant); 5] = [
        ("F_VERTEX_COLOR", MaterialVariant::VERTEX_COLOR),
        ("F_TEXTURE", MaterialVariant::TEXTURE),
        ("F_RAMP", MaterialVariant::RAMP),
        ("F_LIVE_TEX", MaterialVariant::LIVE_TEX),
        ("F_NORMAL_MAP", MaterialVariant::NORMAL_MAP),
    ];

    /// The flags that actually do something. Anything outside this is declared,
    /// hashed and cached correctly — it just does not do anything yet.
    pub const IMPLEMENTED: MaterialVariant = MaterialVariant(
        MaterialVariant::VERTEX_COLOR.0 | MaterialVariant::TEXTURE.0 | MaterialVariant::NORMAL_MAP.0,
    );

    pub const fn from_bits(bits: u32) -> MaterialVariant {
        MaterialVariant(bits)
    }

    pub const fn bits(self) -> u32 {
        self.0
    }

    pub const fn contains(self, other: MaterialVariant) -> bool {
        self.0 & other.0 == other.0
    }

    pub const fn is_empty(self) -> bool {
        self.0 == 0
    }

    /// Flags set here but not in [`IMPLEMENTED`](MaterialVariant::IMPLEMENTED).
    pub const fn unimplemented(self) -> MaterialVariant {
        MaterialVariant(self.0 & !MaterialVariant::IMPLEMENTED.0)
    }
}

impl std::ops::BitOr for MaterialVariant {
    type Output = MaterialVariant;
    fn bitor(self, rhs: MaterialVariant) -> MaterialVariant {
        MaterialVariant(self.0 | rhs.0)
    }
}

impl std::ops::BitOrAssign for MaterialVariant {
    fn bitor_assign(&mut self, rhs: MaterialVariant) {
        self.0 |= rhs.0;
    }
}

/// Build the WGSL for one variant: the feature `const`s, then the base source.
///
/// Deliberately the dumbest preprocessor that works — no `#ifdef` grammar, no
/// includes, no token scanning. WGSL const-folds `if (F_X)` on a `const bool`
/// away entirely, so a "disabled" feature costs nothing at runtime, and the
/// base source stays readable as ordinary WGSL.
pub fn variant_source(base: &str, variant: MaterialVariant) -> String {
    let mut out = String::with_capacity(base.len() + 160);
    out.push_str("// generated by runt_core::material::variant_source\n");
    for (name, flag) in MaterialVariant::FLAGS {
        out.push_str("const ");
        out.push_str(name);
        out.push_str(": bool = ");
        out.push_str(if variant.contains(flag) { "true" } else { "false" });
        out.push_str(";\n");
    }
    out.push_str(base);
    out
}

/// A material: uniform payload + variant key (DESIGN §5).
///
/// Small and `Copy` on purpose — it is written straight into the per-instance
/// uniform slot with no indirection, which is what keeps the draw path a plain
/// loop over a sorted list.
#[derive(Component, Clone, Copy, Debug, PartialEq)]
pub struct Material {
    /// Albedo tint, multiplied into vertex color when `VERTEX_COLOR` is set.
    /// Alpha is written to the target but not blended (opaque pass, §5).
    pub base_color: Vec4,
    /// Reserved uniform slot: ramp threshold/softness/… as those variants land.
    /// Uploaded already so adding a ramp never changes the uniform layout.
    pub params: Vec4,
    /// Which baked texture (§7) this material samples, if any.
    ///
    /// A content key, not a pointer — the same handle discipline `MeshRef`
    /// uses, so two materials naming one spec share one bake. It rides on the
    /// material rather than in `params` because it is a *binding*, resolved by
    /// the renderer's texture registry, not a number the shader reads.
    pub texture: Option<TextureHandle>,
    pub variant: MaterialVariant,
}

impl Default for Material {
    fn default() -> Material {
        Material::vertex_colored()
    }
}

impl Material {
    /// Untinted, taking its color from the mesh's vertex colors.
    pub fn vertex_colored() -> Material {
        Material {
            base_color: Vec4::ONE,
            params: Vec4::ZERO,
            texture: None,
            variant: MaterialVariant::VERTEX_COLOR,
        }
    }

    /// A flat color, ignoring whatever the mesh's vertex colors say.
    pub fn flat(base_color: Vec4) -> Material {
        Material {
            base_color,
            params: Vec4::ZERO,
            texture: None,
            variant: MaterialVariant::NONE,
        }
    }

    /// Vertex colors tinted by `base_color`.
    pub fn tinted(base_color: Vec4) -> Material {
        Material {
            base_color,
            ..Material::vertex_colored()
        }
    }

    /// A baked procedural texture (§7), sampled triplanar and crinkled by its
    /// normal map. `base_color` tints it; vertex colors are off, because a
    /// generator's flat per-vertex tint fighting a procedural albedo is never
    /// what anyone wanted.
    pub fn textured(handle: TextureHandle) -> Material {
        Material {
            base_color: Vec4::ONE,
            params: Vec4::ZERO,
            texture: Some(handle),
            variant: MaterialVariant::TEXTURE | MaterialVariant::NORMAL_MAP,
        }
    }
}
